### ISSUE TITLE
Fix recent issues from Drupal queue also for Backdrop

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/tocbot#10]
- [x] [Doesn't work with jQuery update](https://www.drupal.org/project/tocbot/issues/3083623), fixed for D7 but not yet committed (as of 21 Oct 2019)
  - Fixed by PR https://github.com/backdrop-contrib/tocbot/pull/14.
- [x] [Make automatic IDs lowercase](https://www.drupal.org/project/tocbot/issues/3087825), has a working patch for D7
  - Fixed by PR https://github.com/backdrop-contrib/tocbot/pull/14.
- [x] [Local library not recognized](https://www.drupal.org/project/tocbot/issues/3087814), has a working patch for D7.
  - Fixed by [bundling the library into the module](https://github.com/backdrop-contrib/tocbot/issues/11).

Update 22 Oct: There is a new release at https://www.drupal.org/project/tocbot/releases/7.x-1.1 which includes fixes for the issues mentioned above. (I guess the first issue isn't mentioned in the release notes because it was first fixed but the code was then changed by the second issue.)

**Comment by findlabnet** [comment]
I have working port of this module with some small fixes (I do not use Coder Upgrade):
https://github.com/findlabnet/tocbot
Only need to update README.md and .install for variables migration (haven't time for it at this time). 
You can use anything from this repo, hope it help you to release.

**Comment by olafgrabienski** [comment]
@findlabnet Thanks, I'll have a look at your port, it will be helpful!

**Comment by olafgrabienski** [comment]
All sub-tasks fixed, closing.
